steps:
    - id: 'Deploy application to cluster'
      name: 'gcr.io/k8s-skaffold/skaffold:v0.20.0'
      entrypoint: 'bash'
      args: 
      - '-c'
      - > 
        gcloud container clusters get-credentials --zone=$_ZONE $_CLUSTER;
        skaffold run -f=skaffold.yaml --default-repo=gcr.io/$PROJECT_ID;
    # Add more power, and more time, for heavy Skaffold build
    timeout: '3600s'
    options:
      machineType: 'N1_HIGHCPU_8'